; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "EFW Agente"
!define PRODUCT_VERSION "1.0"
!define PRODUCT_PUBLISHER "FIAP"
!define PRODUCT_WEB_SITE "https://github.com/felipe-vieira/efw-monitoring"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\wrapper.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "${NSISDIR}\Contrib\Graphics\Icons\modern-install.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; Language Selection Dialog Settings
!define MUI_LANGDLL_REGISTRY_ROOT "${PRODUCT_UNINST_ROOT_KEY}"
!define MUI_LANGDLL_REGISTRY_KEY "${PRODUCT_UNINST_KEY}"
!define MUI_LANGDLL_REGISTRY_VALUENAME "NSIS:Language"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; License page
!insertmacro MUI_PAGE_LICENSE "Efw Monitoramento.txt"
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "English"
!insertmacro MUI_LANGUAGE "PortugueseBR"

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "Setup.exe"
InstallDir "$PROGRAMFILES\EFW Agente"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show

Function .onInit
  !insertmacro MUI_LANGDLL_DISPLAY
FunctionEnd

Section "MainSection" SEC01
  SetOutPath "$INSTDIR\bin"
  SetOverwrite try
  File "wrapper\bin\agente.jar"
  SetOutPath "$INSTDIR\bin\agente_lib"
  File "wrapper\bin\agente_lib\commons-beanutils-1.8.0.jar"
  File "wrapper\bin\agente_lib\commons-beanutils-bean-collections-1.8.0.jar"
  File "wrapper\bin\agente_lib\commons-beanutils-core-1.8.0.jar"
  File "wrapper\bin\agente_lib\commons-codec-1.6.jar"
  File "wrapper\bin\agente_lib\commons-collections-3.2.1.jar"
  File "wrapper\bin\agente_lib\commons-lang-2.5.jar"
  File "wrapper\bin\agente_lib\commons-logging-1.1.1.jar"
  File "wrapper\bin\agente_lib\commons-logging-adapters-1.1.1.jar"
  File "wrapper\bin\agente_lib\commons-logging-api-1.1.1.jar"
  File "wrapper\bin\agente_lib\ezmorph-1.0.6.jar"
  File "wrapper\bin\agente_lib\fluent-hc-4.2.jar"
  File "wrapper\bin\agente_lib\httpclient-4.2.jar"
  File "wrapper\bin\agente_lib\httpclient-cache-4.2.jar"
  File "wrapper\bin\agente_lib\httpcore-4.2.jar"
  File "wrapper\bin\agente_lib\httpmime-4.2.jar"
  File "wrapper\bin\agente_lib\jboss-as-controller-client-7.0.2.Final.jar"
  File "wrapper\bin\agente_lib\jboss-as-protocol-7.0.2.Final.jar"
  File "wrapper\bin\agente_lib\jboss-dmr-1.0.0.Final.jar"
  File "wrapper\bin\agente_lib\jboss-logging-3.0.1.GA.jar"
  File "wrapper\bin\agente_lib\jboss-marshalling-1.3.0.GA.jar"
  File "wrapper\bin\agente_lib\jboss-remoting-3.2.0.Beta2.jar"
  File "wrapper\bin\agente_lib\jboss-sasl-1.0.0.Beta2.jar"
  File "wrapper\bin\agente_lib\jboss-threads-2.0.0.GA.jar"
  File "wrapper\bin\agente_lib\json-lib-2.4-jdk15.jar"
  File "wrapper\bin\agente_lib\jtds-1.2.5.jar"
  File "wrapper\bin\agente_lib\junit-4.10.jar"
  File "wrapper\bin\agente_lib\libsigar-amd64-freebsd-6.so"
  File "wrapper\bin\agente_lib\libsigar-amd64-linux.so"
  File "wrapper\bin\agente_lib\libsigar-amd64-solaris.so"
  File "wrapper\bin\agente_lib\libsigar-ia64-hpux-11.sl"
  File "wrapper\bin\agente_lib\libsigar-ia64-linux.so"
  File "wrapper\bin\agente_lib\libsigar-pa-hpux-11.sl"
  File "wrapper\bin\agente_lib\libsigar-ppc-aix-5.so"
  File "wrapper\bin\agente_lib\libsigar-ppc-linux.so"
  File "wrapper\bin\agente_lib\libsigar-ppc64-aix-5.so"
  File "wrapper\bin\agente_lib\libsigar-ppc64-linux.so"
  File "wrapper\bin\agente_lib\libsigar-s390x-linux.so"
  File "wrapper\bin\agente_lib\libsigar-sparc-solaris.so"
  File "wrapper\bin\agente_lib\libsigar-sparc64-solaris.so"
  File "wrapper\bin\agente_lib\libsigar-universal-macosx.dylib"
  File "wrapper\bin\agente_lib\libsigar-universal64-macosx.dylib"
  File "wrapper\bin\agente_lib\libsigar-x86-freebsd-5.so"
  File "wrapper\bin\agente_lib\libsigar-x86-freebsd-6.so"
  File "wrapper\bin\agente_lib\libsigar-x86-linux.so"
  File "wrapper\bin\agente_lib\libsigar-x86-solaris.so"
  File "wrapper\bin\agente_lib\ojdbc14.jar"
  File "wrapper\bin\agente_lib\sigar-amd64-winnt.dll"
  File "wrapper\bin\agente_lib\sigar-x86-winnt.dll"
  File "wrapper\bin\agente_lib\sigar-x86-winnt.lib"
  File "wrapper\bin\agente_lib\sigar.jar"
  File "wrapper\bin\agente_lib\xnio-api-3.0.0.Beta3.jar"
  File "wrapper\bin\agente_lib\xnio-nio-3.0.0.Beta3.jar"
  SetOutPath "$INSTDIR\bin"
  File "wrapper\bin\install.bat"
  File "wrapper\bin\start.bat"
  CreateShortCut "$STARTMENU\Iniciar Agente EFW.lnk" "$INSTDIR\bin\start.bat"
  File "wrapper\bin\stop.bat"
  CreateShortCut "$STARTMENU\Parar agente EFW.lnk" "$INSTDIR\bin\stop.bat"
  File "wrapper\bin\uninstall.bat"
  File "wrapper\bin\wrapper.exe"
  SetOutPath "$INSTDIR\conf"
  File "wrapper\conf\wrapper.conf"
  SetOutPath "$INSTDIR\doc"
  File "wrapper\doc\wrapper-community-license-1.1.txt"
  SetOutPath "$INSTDIR\lib"
  File "wrapper\lib\wrapper.dll"
  File "wrapper\lib\wrapper.jar"
  File "wrapper\lib\wrapperdemo.jar"
  File "wrapper\lib\wrappertest.jar"
  SetOutPath "$INSTDIR\logs"
  File "wrapper\logs\wrapper.log"
  ; Instala e inicia o servico
  ExecWait "$INSTDIR\bin\install.bat"
  ExecWait "$INSTDIR\bin\start.bat"
SectionEnd

Section -AdditionalIcons
  SetOutPath $INSTDIR
  CreateDirectory "$SMPROGRAMS\EFW Monitoramento - Agente"
  CreateShortCut "$SMPROGRAMS\EFW Monitoramento - Agente\Uninstall.lnk" "$INSTDIR\uninst.exe"
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\bin\wrapper.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\bin\wrapper.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) was successfully removed from your computer."
FunctionEnd

Function un.onInit
!insertmacro MUI_UNGETLANGUAGE
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "Are you sure you want to completely remove $(^Name) and all of its components?" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  ; Para e desinstala o serviço antes de tudo
  ExecWait "$INSTDIR\bin\stop.bat"
  ExecWait "$INSTDIR\bin\uninstall.bat"
  Delete "$INSTDIR\uninst.exe"
  Delete "$INSTDIR\logs\wrapper.log"
  Delete "$INSTDIR\lib\wrappertest.jar"
  Delete "$INSTDIR\lib\wrapperdemo.jar"
  Delete "$INSTDIR\lib\wrapper.jar"
  Delete "$INSTDIR\lib\wrapper.dll"
  Delete "$INSTDIR\doc\wrapper-community-license-1.1.txt"
  Delete "$INSTDIR\conf\wrapper.conf"
  Delete "$INSTDIR\bin\wrapper.exe"
  Delete "$INSTDIR\bin\uninstall.bat"
  Delete "$INSTDIR\bin\stop.bat"
  Delete "$INSTDIR\bin\start.bat"
  Delete "$INSTDIR\bin\install.bat"
  Delete "$INSTDIR\bin\agente_lib\xnio-nio-3.0.0.Beta3.jar"
  Delete "$INSTDIR\bin\agente_lib\xnio-api-3.0.0.Beta3.jar"
  Delete "$INSTDIR\bin\agente_lib\sigar.jar"
  Delete "$INSTDIR\bin\agente_lib\sigar-x86-winnt.lib"
  Delete "$INSTDIR\bin\agente_lib\sigar-x86-winnt.dll"
  Delete "$INSTDIR\bin\agente_lib\sigar-amd64-winnt.dll"
  Delete "$INSTDIR\bin\agente_lib\ojdbc14.jar"
  Delete "$INSTDIR\bin\agente_lib\libsigar-x86-solaris.so"
  Delete "$INSTDIR\bin\agente_lib\libsigar-x86-linux.so"
  Delete "$INSTDIR\bin\agente_lib\libsigar-x86-freebsd-6.so"
  Delete "$INSTDIR\bin\agente_lib\libsigar-x86-freebsd-5.so"
  Delete "$INSTDIR\bin\agente_lib\libsigar-universal64-macosx.dylib"
  Delete "$INSTDIR\bin\agente_lib\libsigar-universal-macosx.dylib"
  Delete "$INSTDIR\bin\agente_lib\libsigar-sparc64-solaris.so"
  Delete "$INSTDIR\bin\agente_lib\libsigar-sparc-solaris.so"
  Delete "$INSTDIR\bin\agente_lib\libsigar-s390x-linux.so"
  Delete "$INSTDIR\bin\agente_lib\libsigar-ppc64-linux.so"
  Delete "$INSTDIR\bin\agente_lib\libsigar-ppc64-aix-5.so"
  Delete "$INSTDIR\bin\agente_lib\libsigar-ppc-linux.so"
  Delete "$INSTDIR\bin\agente_lib\libsigar-ppc-aix-5.so"
  Delete "$INSTDIR\bin\agente_lib\libsigar-pa-hpux-11.sl"
  Delete "$INSTDIR\bin\agente_lib\libsigar-ia64-linux.so"
  Delete "$INSTDIR\bin\agente_lib\libsigar-ia64-hpux-11.sl"
  Delete "$INSTDIR\bin\agente_lib\libsigar-amd64-solaris.so"
  Delete "$INSTDIR\bin\agente_lib\libsigar-amd64-linux.so"
  Delete "$INSTDIR\bin\agente_lib\libsigar-amd64-freebsd-6.so"
  Delete "$INSTDIR\bin\agente_lib\junit-4.10.jar"
  Delete "$INSTDIR\bin\agente_lib\jtds-1.2.5.jar"
  Delete "$INSTDIR\bin\agente_lib\json-lib-2.4-jdk15.jar"
  Delete "$INSTDIR\bin\agente_lib\jboss-threads-2.0.0.GA.jar"
  Delete "$INSTDIR\bin\agente_lib\jboss-sasl-1.0.0.Beta2.jar"
  Delete "$INSTDIR\bin\agente_lib\jboss-remoting-3.2.0.Beta2.jar"
  Delete "$INSTDIR\bin\agente_lib\jboss-marshalling-1.3.0.GA.jar"
  Delete "$INSTDIR\bin\agente_lib\jboss-logging-3.0.1.GA.jar"
  Delete "$INSTDIR\bin\agente_lib\jboss-dmr-1.0.0.Final.jar"
  Delete "$INSTDIR\bin\agente_lib\jboss-as-protocol-7.0.2.Final.jar"
  Delete "$INSTDIR\bin\agente_lib\jboss-as-controller-client-7.0.2.Final.jar"
  Delete "$INSTDIR\bin\agente_lib\httpmime-4.2.jar"
  Delete "$INSTDIR\bin\agente_lib\httpcore-4.2.jar"
  Delete "$INSTDIR\bin\agente_lib\httpclient-cache-4.2.jar"
  Delete "$INSTDIR\bin\agente_lib\httpclient-4.2.jar"
  Delete "$INSTDIR\bin\agente_lib\fluent-hc-4.2.jar"
  Delete "$INSTDIR\bin\agente_lib\ezmorph-1.0.6.jar"
  Delete "$INSTDIR\bin\agente_lib\commons-logging-api-1.1.1.jar"
  Delete "$INSTDIR\bin\agente_lib\commons-logging-adapters-1.1.1.jar"
  Delete "$INSTDIR\bin\agente_lib\commons-logging-1.1.1.jar"
  Delete "$INSTDIR\bin\agente_lib\commons-lang-2.5.jar"
  Delete "$INSTDIR\bin\agente_lib\commons-collections-3.2.1.jar"
  Delete "$INSTDIR\bin\agente_lib\commons-codec-1.6.jar"
  Delete "$INSTDIR\bin\agente_lib\commons-beanutils-core-1.8.0.jar"
  Delete "$INSTDIR\bin\agente_lib\commons-beanutils-bean-collections-1.8.0.jar"
  Delete "$INSTDIR\bin\agente_lib\commons-beanutils-1.8.0.jar"
  Delete "$INSTDIR\bin\agente.jar"

  Delete "$SMPROGRAMS\EFW Monitoramento - Agente\Uninstall.lnk"
  Delete "$STARTMENU\Parar agente EFW.lnk"
  Delete "$STARTMENU\Iniciar Agente EFW.lnk"

  RMDir "$SMPROGRAMS\EFW Monitoramento - Agente"
  RMDir "$STARTMENU"
  RMDir "$INSTDIR\logs"
  RMDir "$INSTDIR\lib"
  RMDir "$INSTDIR\doc"
  RMDir "$INSTDIR\conf"
  RMDir "$INSTDIR\bin\agente_lib"
  RMDir "$INSTDIR\bin"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  SetAutoClose true
SectionEnd